# Site wide configuration
remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: fr_FR
title: Photos des rencontres
description: Les photos des rencontres
baseurl: "/" 
url: "https://amazones.fcg.photos.fleuri.fr/"
logo: "/images/site-logo.jpg" 
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
#  combo: "tex-mml-chtml"
#  tags: "none"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
# twitter:
#   username: mmistakes # site's Twitter username

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

# Collections
# collections:
#   recipes:
#     output: true
#     permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false
 
 # Site Author
author:
  name: Frédéric Fleuri
  picture: /images/author_frederic.jpg
  email: